name: api-main

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/api-main.yaml
      - api/**
  schedule:
    - cron: '0 0 * * *'  # every day at midnight
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow pushing a conatainer image to ghcr.io
permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  api-build-lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.10' 
      - name: Install dependencies
        run: make install
        working-directory: api
      - name: Lint and typecheck
        run: make check
        working-directory: api
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Run API tests
        run: make bruno-tests
        working-directory: api

  api-publish-container:
    needs: api-build-lint-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          context: api
          containerfiles: api/Containerfile
          image: majorityreports/api
          tags: next
          oci: true

      - name: Push to GitHub
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Push to Quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

  api-publish-container-ubi9:
    needs: api-build-lint-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          context: api
          containerfiles: api/Containerfile.ubi9
          image: majorityreports/api-ubi9
          tags: next
          oci: true

      - name: Push to GitHub
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Push to Quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
