name: api-publish-container-ubi9

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/api-publish-container-ubi9.yaml
      - api/**
  schedule:
    - cron: '0 0 * * *'  # every day at midnight
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow pushing a conatainer image to ghcr.io
permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  api-publish-container-ubi9:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          context: api
          containerfiles: api/Containerfile.ubi9
          image: majorityreports/api-ubi9
          tags: next
          oci: true

      - name: Push to GitHub
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Push to Quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
