name: api-pr

on:
  push:
    branches-ignore:
      - main
    paths:
      - .github/workflows/api-pr.yaml
      - api/**
  pull_request:

jobs:
  api-build-lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.10' 
      - name: Install dependencies
        run: make install
        working-directory: api
      - name: Lint and typecheck
        run: make check
        working-directory: api
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Run API tests
        run: make bruno-tests
        working-directory: api
