name: website-pr

on:
  push:
    branches-ignore:
      - main
    paths:
      - .github/workflows/website-pr.yaml
      - website/**

jobs:
  website-publish-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install website dependencies
        run: npm ci
        working-directory: website
      - name: Build website
        run: npm run build
        working-directory: website
