name: website-main

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/website-main.yaml
      - website/**

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  website-publish-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install website dependencies
        run: npm ci
        working-directory: website
      - name: Build website
        run: npm run build
        working-directory: website
      - name: Upload GitHub page
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./website/build
      - name: Deploy GitHub Page
        uses: actions/deploy-pages@v4
